# Generated by Django 5.0 on 2023-12-21 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user_profile_images/', verbose_name='Profile Image')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
