version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    image: nithin058/django-ecommerce:latest
    container_name: django_app
    command: gunicorn ecom_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - /mnt/logs/django:/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
