apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ecommerce-ingress
  labels:
    app: django-ecommerce
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: django-ecommerce.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-ecommerce-service
            port:
              number: 80
